modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="https://github.com/skippi/overeat/issues"

[[mods]]
modId="overeat"
version="${file.jarVersion}"
displayName="overeat"
# updateJSONURL="http://myurl.me/"
displayURL="https://github.com/skippi/overeat"
logoFile="logo.png"
credits="Minecraft Forge team"
authors="skippi"
description='''
A minecraft forge mod that makes every item edible regardless of hunger.
'''

[[dependencies.overeat]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.overeat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
